<?php

namespace App\Helpers;

class Constants
{
    public const WORK_INDUSTRIES = [
        "Accounting",
        "Advertising",
        "Apparel",
        "Architecture",
        "Arts",
        "Automobile",
        "Aviation",
        "Banking",
        "Beauty",
        "BioTech",
        "Business",
        "BPO / Call Center",
        "Chemical",
        "Construction",
        "Consumer Products",
        "Education",
        "Electrical & Electronics",
        "Engineering",
        "Entertainment",
        "Environment",
        "Exhibitions",
        "Food & Beverage",
        "Gems",
        "General & Wholesale Trading",
        "Goverment",
        "Healthcare",
        "Heavy Industrial",
        "Hotel",
        "HR Management",
        "Insurance",
        "IT",
        "Journalism",
        "Law",
        "Libarary",
        "Manufacturing",
        "Marine",
        "Mining",
        "Oil",
        "Polymer",
        "Printing",
        "Property",
        "Repair",
        "Retail",
        "Science & Technology",
        "Security",
        "Semiconductor",
        "Social Services",
        "Sports",
        "Stockbroking",
        "Telecommunication",
        "Textiles",
        "Tobacco",
        "Transportation",
        "Travel",
        "Utilities",
        "Wood",
        "Others"
    ];
    public const HTTP_STATUS_CODE_OK = 200;
}
